version: '3.8'

services:

  postgre-elastic-sync:
    container_name: postgre-elastic-sync
    image: 'postgre-elastic-sync'
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgre
    env_file:
      - .env

  postgre:
    container_name: postgre
    image: 'postgres'
    ports:
      - "5432:5432"
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - cluster.name=demo-es-postgres
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.0.0
    volumes:
      - ./logstash/config-dir:/usr/share/logstash/config-dir
      - ./logstash/drivers/:/usr/share/logstash/drivers
    command: logstash -f /usr/share/logstash/config-dir/logstash.conf
    env_file:
      - .env
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

#  kibana:
#    container_name: kibana
#    image: docker.elastic.co/kibana/kibana:7.2.0
#    ports:
#      - "5601:5601"
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
